version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: |
        echo $DOCKER_PASSOWRD | docker login -u $DOCKER_USER --password-stdin
        docker build . -t jchancehud/circle-artifacts-redirect
        docker push jchancehud/circle-artifacts-redirect
workflows:
  version: 2
  build_all:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - master
