master: &Master |
  docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  docker build . -t jchancehud/circle-artifacts-redirect
  docker push jchancehud/circle-artifacts-redirect

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: *Master
workflows:
  version: 2
  build_all:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - master
