docker_login: &DockerLogin |
  docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: *DockerLogin
      - run: docker build . -t jchancehud/circle-artifacts-redirect
      - run: docker push jchancehud/circle-artifacts-redirect
workflows:
  version: 2
  build_all:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - master
